export const FETCH_REVIEWS_REQUEST = 'FETCH_REVIEWS_REQUEST';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAILURE = 'FETCH_REVIEWS_FAILURE';

export const SORT_REVIEWS_UP = 'SORT_REVIEWS_UP';
export const SORT_REVIEWS_DOWN = 'SORT_REVIEWS_DOWN';

export const EDIT_REVIEW = 'EDIT_REVIEW';
