export const FETCH_REVIEWS_REQUEST = 'FETCH_REVIEWS_REQUEST';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAILURE = 'FETCH_REVIEWS_FAILURE';

export const UPDATE_REVIEWS = 'UPDATE_REVIEWS';

export const EDIT_REVIEW = 'EDIT_REVIEW';
