export const FETCH_REVIEWS_REQUEST = 'FETCH_REVIEWS_REQUEST';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAILURE = 'FETCH_REVIEWS_FAILURE';

export const SORT_REVIEWS_UP_BY_RATING = 'SORT_REVIEWS_UP_BY_RATING';
export const SORT_REVIEWS_DOWN_BY_RATING = 'SORT_REVIEWS_DOWN_BY_RATING';

export const EDIT_REVIEW = 'EDIT_REVIEW';
